name: 'Odet Service Upload'
description: 'Uploads your service yml to Odet portal'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  odet-file:
    required: true
  api-key:
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
